#!/usr/bin/env python3
"""Generated-view builder for the SyllabAI coordination state.

Writes/refreshes `TODO-CURRENT.md` at the repo root: a compact projection
of `.syllabai/tasks/*.yaml` (open packets grouped by status, then closed
packets). `TODO.md` remains the full canonical queue — this file is a
lens, never a replacement, and says so in its header.

Also prints a parity report between packet statuses and TODO.md checkbox
lines (drift detector for the duplication that past documentation
accuracy audits kept finding):

  OPEN_PACKET_NOT_IN_TODO   packet not DONE but absent from TODO.md open items
  DONE_BUT_LISTED_OPEN      packet DONE but TODO.md still lists it open
  TODO_OPEN_NO_PACKET       open TODO.md T-Cxx-style id with no packet file

Modes:
  --write   regenerate TODO-CURRENT.md (default; local/agent use)
  --check   compute the view, compare with the committed file, report
            drift; exit 1 in strict mode, else warn-only

This tool is READ-ONLY over coordination inputs: it never edits task
packets, TODO.md, PROGRESS.md or locks.yaml.
"""

import argparse
import re
import sys
from pathlib import Path

import yaml

# Open = anything not DONE (unknown/illegal statuses are conservative-open:
# a task that has not reached DONE must stay visible in the frontier).
KNOWN_OPEN = ["READY", "BLOCKED", "EXECUTING", "VERIFYING"]
STATUS_ORDER = {s: i for i, s in enumerate(KNOWN_OPEN)}
GENERATED_MARKER = "<!-- GENERATED by .syllabai/tools/gen_views.py — do not edit by hand; rerun the script. -->"
TODO_ID_RE = re.compile(r"^-\s*\[( |x)\]\s*(T-[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*)", re.MULTILINE)


def load_packets(tasks_dir: Path):
    packets = []
    for path in sorted(tasks_dir.glob("*.yaml")):
        if path.name.upper().startswith("README"):
            continue
        try:
            with open(path, "r", encoding="utf-8") as fh:
                doc = yaml.safe_load(fh)
        except yaml.YAMLError:
            packets.append({"file": path.name, "id": path.stem, "status": "UNPARSEABLE",
                            "title": "(yaml parse error)", "owner": ""})
            continue
        task = (doc or {}).get("task") if isinstance(doc, dict) else None
        if not isinstance(task, dict):
            packets.append({"file": path.name, "id": path.stem, "status": "UNPARSEABLE",
                            "title": "(no task mapping)", "owner": ""})
            continue
        packets.append({
            "file": path.name,
            "id": str(task.get("id") or path.stem),
            "status": str(task.get("status") or "UNKNOWN"),
            "title": str(task.get("title") or "").strip().replace("\n", " "),
            "owner": str(task.get("owner") or "").strip(),
        })
    return packets


def parse_todo_ids(todo_md: Path):
    open_ids, done_ids = set(), set()
    if not todo_md.is_file():
        return open_ids, done_ids
    text = todo_md.read_text(encoding="utf-8", errors="replace")
    for mark, tid in TODO_ID_RE.findall(text):
        (done_ids if mark == "x" else open_ids).add(tid)
    return open_ids, done_ids


def render_view(packets) -> str:
    open_packets = sorted((p for p in packets if p["status"] != "DONE"),
                          key=lambda p: (STATUS_ORDER.get(p["status"], 50), p["status"], p["id"]))
    closed = sorted((p for p in packets if p["status"] == "DONE"),
                    key=lambda p: p["id"], reverse=True)

    lines = [
        GENERATED_MARKER,
        "",
        "# TODO-CURRENT — compact packet view",
        "",
        "**Scope note:** this file is a *generated projection* of `.syllabai/tasks/*.yaml` only.",
        "`TODO.md` remains the full canonical queue (wave tasks, closed history, sub-rows) and is",
        "never replaced by this view. Agents may read this file first for the open-packet frontier,",
        "then consult `TODO.md` / the packet YAMLs for detail.",
        "",
        f"_Packet census: {len(open_packets)} open / {len(closed)} closed / {len(packets)} total._",
        "",
    ]
    if open_packets:
        lines.append("## Open packets")
        lines.append("")
        current = None
        for p in open_packets:
            if p["status"] != current:
                current = p["status"]
                lines.append(f"### {current}")
                lines.append("")
            owner = f" — owner: {p['owner']}" if p["owner"] else ""
            title = p["title"][:160] + ("…" if len(p["title"]) > 160 else "")
            lines.append(f"- **{p['id']}** (`{p['file']}`){owner} — {title}")
        lines.append("")
    else:
        lines.append("## Open packets")
        lines.append("")
        lines.append("_None._")
        lines.append("")
    if closed:
        lines.append("## Closed packets")
        lines.append("")
        for p in closed:
            title = p["title"][:120] + ("…" if len(p["title"]) > 120 else "")
            lines.append(f"- {p['id']} — {title}")
        lines.append("")
    return "\n".join(lines) + "\n"


def parity_report(packets, open_ids, done_ids):
    findings = []
    packet_ids = {p["id"] for p in packets}
    for p in packets:
        if p["status"] != "DONE" and p["id"] not in open_ids:
            findings.append(("OPEN_PACKET_NOT_IN_TODO", p["id"],
                             f"packet status {p['status']} but TODO.md has no open checkbox for it"))
        if p["status"] == "DONE" and p["id"] in open_ids:
            findings.append(("DONE_BUT_LISTED_OPEN", p["id"],
                             "packet is DONE but TODO.md still lists it as an open item"))
    for tid in sorted(open_ids):
        if tid not in packet_ids and re.match(r"^T-C\d+", tid):
            findings.append(("TODO_OPEN_NO_PACKET", tid,
                             "open TODO.md item has no packet in .syllabai/tasks/ (informational — wave tasks legitimately live only in TODO.md)"))
    return findings


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--repo-root", default=".")
    parser.add_argument("--mode", choices=["write", "check"], default="write")
    parser.add_argument("--strict", action="store_true",
                        help="with --mode check, exit 1 on view drift or parity findings")
    parser.add_argument("--summary", default=None)
    args = parser.parse_args()

    root = Path(args.repo_root)
    tasks_dir = root / ".syllabai" / "tasks"
    target = root / "TODO-CURRENT.md"

    packets = load_packets(tasks_dir)
    view = render_view(packets)
    open_ids, done_ids = parse_todo_ids(root / "TODO.md")
    findings = parity_report(packets, open_ids, done_ids)

    drift = None
    if args.mode == "check" and target.is_file():
        committed = target.read_text(encoding="utf-8")
        drift = committed != view

    lines = []
    open_n = sum(1 for p in packets if p["status"] != "DONE")
    done_n = sum(1 for p in packets if p["status"] == "DONE")
    lines.append(f"gen_views: packet census {open_n} open / {done_n} closed / {len(packets)} total")
    if args.mode == "write":
        target.write_text(view, encoding="utf-8")
        lines.append(f"gen_views: wrote {target.name}")
    else:
        if drift is None:
            lines.append(f"gen_views: {target.name} not present (would be created)")
        else:
            lines.append(f"gen_views: {target.name} is {'IN SYNC' if not drift else 'DRIFTED'} with the computed view")
    if findings:
        lines.append(f"gen_views: parity findings: {len(findings)}")
        for kind, tid, detail in findings:
            lines.append(f"  [{kind}] {tid}: {detail}")
    else:
        lines.append("gen_views: parity findings: 0")
    output = "\n".join(lines)

    print(output)
    if args.summary:
        try:
            with open(args.summary, "a", encoding="utf-8") as fh:
                fh.write("## Generated views\n\n```\n" + output + "\n```\n")
        except OSError:
            pass

    if args.mode == "check" and args.strict:
        return 1 if (drift or findings) else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
